### ISSUE TITLE
how to connect to bungee?

### ISSUE THREAD

**Issue by Westloch** [GeorgH93/Minepacks#122]
We've been running minepacks for a few months now and players have things stored in their back packs.

We are now setting up a bungee network and would like the backpacks to link between worlds. I did not find anything in the wiki about bungee setup. So i have a few questions.

~~1.)~~ Does minepacks need to be installed on all servers + proxy, does it ONLY need to be installed on proxy, or does it ONLY need to be installed on backend servers and NOT proxy?

~~2.)Im assuming mysql is needed so servers/data can be linked? How does one go about transferring existing data without losing any of it?~~ _Figured out this part_

**Comment by GeorgH93** [comment]
Minepacks must be installed on all servers (but not on the proxy) that should be able to use the plugin. All your servers must use the same database settings (and I would recommend to set all the other config values the same to, or copy one of your config files to all your servers).
When using a proxy server you should set the `UUID_Type` config option manually since the plugin won't be able to figure out whether your proxy is running in online or offline mode.
Also make sure to enable the `UseBungeeCord` config option.
