### ISSUE TITLE
It could be that this plugin has timed out

### ISSUE THREAD

**Issue by yecangminga** [GeorgH93/Minepacks#225]
[新建 文本文档.txt](https://github.com/GeorgH93/Minepacks/files/9174997/default.txt)

**Comment by GeorgH93** [comment]
The message
`[09:49:20] [Minepacks-Connection-Pool housekeeper/WARN]: [at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.pool.HikariPool] Minepacks-Connection-Pool - Thread starvation or clock leap detected (housekeeper delta=3m13s524ms570?s800ns).`
is just a warning from the database connection pool caused by the server freezing. It's simply a symptom, not the cause of the freez.
