### ISSUE TITLE
Plugin does not work on Paper 1.19.3 405 and newer

### ISSUE THREAD

**Issue by Voyaca** [GeorgH93/Minepacks#249]
### Information
**Environment information**
*Plugin + server version info*:
Minepacks v2.4.12-release. server version 1.19.3
```

Cant do this. Plugin will not enable.

```
Online mode:
yes

Bungee cord:
no

Log:
https://gist.github.com/Voyaca/8b6e862838dd8ca9c7fb3259cee2a1b9
```

<!-- Replace this with your crash log / link to your log file -->

```

I really haven't messed with the config.
```


```

### Details
**Description**  
Minepacks refuses to enable. It was working fine yesterday.

**Steps to reproduce**  
Start server. 

**Expected behavior**  
Consistently refuses to enable upon server startup. 

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)
My Server hosting provider did some funky stuff today that was causing some plugins to have circular dependencies.
This is the startup command they had to add in order for the server to even start up and avoid the issues.
"-Dpaper.useLegacyPluginLoading=true"
Beyond today, the plugin worked perfectly.

**Comment by GeorgH93** [comment]
Which server software are you using? Paper or some fork of it?

**Comment by Voyaca** [comment]
Just Paper

**Comment by mbax** [comment]
If you want to test this you'll need latest Paper build 406

**Comment by GeorgH93** [comment]
I just checked it, looks like their changes for paper plugins broke loading my plugins. I will fix this tomorrow.
Till then, you can either use Paper build number 404 or [Minepacks Standalone](https://github.com/GeorgH93/Minepacks/releases/download/v2.4.12/Minepacks-2.4.12-Standalone.jar) as a workaround.

**Comment by Voyaca** [comment]
Awesome thank you. Will the minepacks stand alone work with the pre-existing Minepacks plugin files?

**Comment by GeorgH93** [comment]
Yes, it will. Everything is the same, except for the plugin loading logic.

**Comment by Voyaca** [comment]
okay thank you so much! Sorry about not being the best when reporting bugs. Still new to this stuff. But ill get back to you if the stand alone has issues!

**Comment by Voyaca** [comment]
IT WORKS! THANK YOU SO MUCH

**Comment by ImFreee** [comment]
same issue paper 409

**Comment by jacklollz2** [comment]
Your plugin is the only one that has this issue. After viewing the source, it appears your BadRabbit system is the cause.
BadRabbit is also a garbage name to use, as BadRabbit is the name of a randsomware.

I am quarantining your plugin on all of my networks henceforuth.

**Comment by Voyaca** [comment]
So is the name just a poor choice of error codes or is it actually randsomeware? 
Do I need to do anything on my end? and should I expect anything on my server?

**Comment by jacklollz2** [comment]
> So is the name just a poor choice of error codes or is it actually randsomeware? Do I need to do anything on my end? and should I expect anything on my server?

I believe it's just poor choice.
https://github.com/GeorgH93/BadRabbit

**Comment by GeorgH93** [comment]
[This build](https://ci.pcgamingfreaks.at/job/Minepacks/315/artifact/a/Minepacks-2.4.13-SNAPSHOT-Release.jar) should add support for paper plugins.



> Your plugin is the only one that has this issue. After viewing the source, it appears your BadRabbit system is the cause. BadRabbit is also a garbage name to use, as BadRabbit is the name of a randsomware.
> 
> I am quarantining your plugin on all of my networks henceforuth.

This plugin supports 11 Major versions of Minecraft. If I would drop that a lot of things would become less of an issue. If you aren't happy about an issue caused by changes in the newest server version you always have to option not to use this **FREE** and OPEN SOURCE plugin. Or build the plugin your self instead of relying on the distribution systems that allow me to upload only one flavor of the plugin (the default build and the standalone build both work fine).

Well it's open source, so you can just check what it is and does. And on top of that it's java so you can even decompile and check the compiled version and unlike all the payed plugins you don't even have to deobfuscate it.
So the name of my plugin bootstrapper is not a great choice. I don't care. And I am way to lazy to change it.

As long as you don't come running when your quarantining breaks my plugin I don't care what you do with it. Use it, don't use it, I don't care.

**Comment by jacklollz2** [comment]
You should drop support for versions prior to 1.13, as it causes a lot of unnecessary trouble for developers.
