### ISSUE TITLE
Backpack command

### ISSUE THREAD

**Issue by Topflight187** [GeorgH93/Minepacks#78]
### Help request

**Problem**
Would like to change the command on the backpack item use. It is interfering with another backpack from the betonquest plugin and does not work. Could I get a copy of the plugin with the command on item use being /minepack instead of /backpack

**What I have tried**
Tried running a script to make your backpack item run a different command on use but still no luck.

**Comment by GeorgH93** [comment]
Should be fixed with this build: https://ci.pcgamingfreaks.at/job/Minepacks/187/artifact/a/Minepacks-2.3.5-RC2-Release.jar
It will now use the primary translation of the command. The primary translation is the first listed in the language file.


Example: 
```yaml
Command:
  Backpack:
    - minepacks
    - backpack
    - bp
  Open:
    - open
```
Should make the shortcut use `/minepacks open`.

**Comment by Topflight187** [comment]
thank you!
