### ISSUE TITLE
API.

### ISSUE THREAD

**Issue by FUZIK** [GeorgH93/Minepacks#9]
please add "name" parameter to "openBackpack(opener,owner,editable)" function.

`
openBackpack(player,player,false,"this my custom name of my backpack");
`

[thanks.](https://forums.skunity.com/resources/skuniversal.289/)

**Comment by GeorgH93** [comment]
Sorry it has taken that long.
I finally found the time and added it to the upcoming V2.0 update: https://github.com/GeorgH93/Minepacks/commit/71b2e3f44749528cda830eff3669691412cc9022

Since you are hocking into the plugin there are some things to note:
V2.0 will also chance a lot of internal stuff including the package name/locations and will add an real API.
Also the plugin name has been streamlined and will be Minepacks everywhere.
Due to the fact that the plugin name in the plugin.yml has been chanced you should be able to support old V1.x versions as well as the new V2.x versions by checking weather MinePacks or Minepacks is installed on the server.
To ensure that further updates of V2.x builds don't break anything, please use the API for access to internal data of the plugin. https://github.com/GeorgH93/Minepacks/tree/V2/src/at/pcgamingfreaks/Minepacks/Bukkit/API

In case you would like to test it:
You can find the V2.0 build here: https://ci.pcgamingfreaks.at/job/Minepacks%20V2/
You will also need to add a library plugin which can be found here: https://ci.pcgamingfreaks.at/job/PluginLib/
